JDP191002-11 - added entity Order
interceptor2048/project-jdp-1910-02 pull request #18
Opened 2019-10-25 22:48 UTC by Sewerinski

2019-10-27 09:14 UTC, szpila127 commented on src/main/java/com/kodilla/ecommercee/domain/Order.java
> +    @JoinColumn(name = "user_id", referencedColumnName = "id")
referencedColumnName jest chyba Niewymagany nie ? W Encji User jak zrobimy w OneToMany w mappedBy = "user"
Ale też nie przeszkadza nic nie ? :)

2019-10-27 22:57 UTC, Sewerinski commented on src/main/java/com/kodilla/ecommercee/domain/Order.java
> +    @JoinColumn(name = "user_id", referencedColumnName = "id")
poprawiłem :)

2019-10-28 05:41 UTC, interceptor2048 requested changes

2019-10-28 05:41 UTC, interceptor2048 commented on src/main/java/com/kodilla/ecommercee/domain/Order.java
> +    //private User user;
Dlaczego nie mamy tej relacji skoro klasa `User` już istnieje (poniżej)?

2019-10-28 16:55 UTC, Sewerinski commented on src/main/java/com/kodilla/ecommercee/domain/Order.java
> +    //private User user;
Bo klasa User nie jest skończona i jak teraz dodam swoje połączenie kolumn to mi wywala błąd, gradle się nie "bilduje" i aplikacja nie rusza. I teraz właśnie pytanie, czy mam sam implementować z Userze co potrzebuję choć to nie moje zadanie? Czy zostawiać tak jak jest i czekać aż dojedzie User?

2019-10-28 19:41 UTC, interceptor2048 approved these changes

2019-10-28 20:26 UTC, tsloka approved these changes

2019-10-28 20:29 UTC, merged