JDP191002-24 - full implementation of OrderController + new packages
interceptor2048/project-jdp-1910-02 pull request #21
Opened 2019-10-30 22:50 UTC by Sewerinski

2019-10-30 23:39 UTC, szpila127 approved these changes

2019-10-31 06:38 UTC, interceptor2048 requested changes

2019-10-31 06:38 UTC, interceptor2048 commented on src/main/java/com/kodilla/ecommercee/domain/dto/OrderDto.java
> +    private User user;
Jeżeli to jest `OrderDto` to powinno być wskazanie na `UserDto` i `CartDto`

2019-11-03 17:00 UTC, kwisniowski requested changes

2019-11-03 17:00 UTC, kwisniowski commented on src/main/java/com/kodilla/ecommercee/controller/OrderController.java
> +@RequestMapping("/v1/order")
Nie lepiej zostawić /v1/ecommerce/  ? 
W ten sposób mamy jeden adres do frontendu i zmieniają się tylko nazwy metod czyli do /v1/ecommerce/ wklejamy anbo getOrder, albo getUser, albo createCart itd...

2019-11-04 19:59 UTC, kwisniowski approved these changes

2019-11-04 20:14 UTC, kwisniowski approved these changes

2019-11-04 20:53 UTC, szpila127 commented on src/main/java/com/kodilla/ecommercee/controller/OrderController.java
> +@RequestMapping("/v1/order")
ecommercee/order

2019-11-04 20:55 UTC, Sewerinski commented on src/main/java/com/kodilla/ecommercee/controller/OrderController.java
> +@RequestMapping("/v1/order")
info na czacie

2019-11-04 21:01 UTC, szpila127 requested changes
Controller -> adres
ecommercee/order
 ??

2019-11-04 21:08 UTC, szpila127 approved these changes

2019-11-05 14:17 UTC, interceptor2048 approved these changes

2019-11-05 14:18 UTC, merged