Full userController, +mapper +repository +service
interceptor2048/project-jdp-1910-02 pull request #23
Opened 2019-11-03 16:55 UTC by kwisniowski

UserController w wersji docelowej plus klasy mappera, repository i service. Dodatkowo w domain stworzyłem klasę Token, która będzie reprezentować ważne przez godzinę, losowe hasło dostępu (za pomocą kodów ascii liczb i małych liter).

2019-11-04 15:32 UTC, rafalkieras commented on src/main/java/com/kodilla/ecommercee/controller/UserController.java
> +        else return "Invalid user data";
Tutaj raczej bym rzucił jakiś wyjątek

2019-11-04 15:32 UTC, rafalkieras commented on src/main/java/com/kodilla/ecommercee/controller/exception/UserNotFoundException.java
> +public class UserNotFoundException extends Exception{
Osobiście rozszerzyłbym tutaj `RuntimeException` , nie musimy wtedy deklarować na poziomie metody kontrolera `throws UserNotFoundException`

2019-11-04 15:32 UTC, rafalkieras commented on src/main/java/com/kodilla/ecommercee/domain/dto/UserDto.java
> +@Getter
Te adnotacje (`@Getter` i `@Setter`) nie wydają się być tutaj potrzebne

2019-11-04 15:32 UTC, rafalkieras commented on src/main/java/com/kodilla/ecommercee/mapper/UserMapper.java
> +    public List<UserDto> mapToUserDtoList(final List<User> userList) {
Nieużywana metoda

2019-11-04 20:04 UTC, kwisniowski commented on src/main/java/com/kodilla/ecommercee/controller/UserController.java
> +        else return "Invalid user data";
Miałem takie przeczucie, ze będzie lepiej ale jakoś o tym zapomniałem.

2019-11-04 20:05 UTC, kwisniowski commented on src/main/java/com/kodilla/ecommercee/controller/exception/UserNotFoundException.java
> +public class UserNotFoundException extends Exception{
Good point.

2019-11-04 20:06 UTC, kwisniowski commented on src/main/java/com/kodilla/ecommercee/mapper/UserMapper.java
> +    public List<UserDto> mapToUserDtoList(final List<User> userList) {
To poszło z rozpędu. Usunięte.

2019-11-04 20:08 UTC, kwisniowski commented on src/main/java/com/kodilla/ecommercee/domain/dto/UserDto.java
> +@Getter
Setter jest mi potrzebny bo po znalezieniu użytkownika, na UserDto dokonuję blokowania przez zmianę  pola isBlocked.

2019-11-04 21:33 UTC, tsloka requested changes
Jeden drobiazg, jak skupiamy się na wykorzystaniu lombok`a, to wrzuć w UserDto automatycznie generowane gettery i allArgsConstructor ;)

2019-11-04 22:54 UTC, kwisniowski commented
> Jeden drobiazg, jak skupiamy się na wykorzystaniu lombok`a, to wrzuć w UserDto automatycznie generowane gettery i allArgsConstructor ;)

2019-11-04 22:55 UTC, kwisniowski commented
Zostało to usunięte przez mentora - niepotrzebne to do wyrzucenia, bez zbędnych adnotacji....

2019-11-04 23:15 UTC, tsloka submitted a review, later dismissed

2019-11-04 23:46 UTC, tsloka approved these changes

2019-11-05 07:38 UTC, rafalkieras approved these changes

2019-11-05 07:47 UTC, merged