User and Order Tests
interceptor2048/project-jdp-1910-02 pull request #36
Opened 2019-11-15 19:16 UTC by SkylineSG

2019-11-16 20:40 UTC, OhdeD commented on src/test/java/com/kodilla/ecommercee/domain/OrderEntityTestSuite.java
> +        Order third = new Order(3L,"Third",300.0,null,null);
Myślę, że można byłoby stworzyć dodatkowy konstruktor w Order, żeby te nulle nie biły tak po oczach.. Nie trzeba będzie zmieniać dalej w kodzie, a później w Jsonie też uniknęlibyśmy ich wypisywania.

2019-11-16 20:51 UTC, OhdeD commented on src/test/java/com/kodilla/ecommercee/domain/UserEntityTestSuite.java
> +        long findRick = rick.getUserId();
Id powinno się samo generować przy tworzeniu nowego użytkownika więc możnaby je pominąć w konstruktorze (w teście powyżej również). I wtedy pobranie ID z tego właśnie tworzonego usera Ricka można wykorzystać w metodzie findUser, która mogłaby się tu znaleźć.
W takiej formie test nie szuka Usera w bazie wg mnie.

2019-11-16 20:53 UTC, OhdeD requested changes
Zmieniłabym ostatnią metodę i dodałabym //Given żeby ładnie wyglądało wszystko.
Niektóre entery też wywaliłabym. Poza tym giatara :)

2019-11-17 17:21 UTC, SkylineSG reviewed
Dodane //Giveny ;)

2019-11-18 21:44 UTC, tsloka approved these changes

2019-11-19 14:58 UTC, OhdeD approved these changes

2019-11-19 16:10 UTC, merged